import Head from 'next/head';
import { Inter } from '@next/font/google';
import GitHubSignInButton from '../component/GitHubSignInButton';
import useGitHubOAuthAccess from '../hooks/useGitHubOAuthAccess';
import styles from '../styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

export default function Users() {
  const databaseId = useGitHubOAuthAccess();
  return (
    <>
      <Head>
        <title>Users</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          {databaseId ? <GitHubSignInButton /> : databaseId}
        </div>
      </main>
    </>
  );
}
